name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  debian-bookworm:
    if: true
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: apt-get -y update && apt-get install -y build-essential cmake

      - name: Cmake
        run: cmake -B build -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D BUILD_SHARED_LIBS=ON

      - name: Build
        run: cmake --build build --config Release

  fedora-latest:
    if: true
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: dnf -y install cmake gcc gcc-c++

      - name: Cmake
        run: cmake -B build -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D BUILD_SHARED_LIBS=ON

      - name: Build
        run: cmake --build build --config Release

  windows-latest-x64:
    if: true
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Cmake
        run: cmake -B build -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D BUILD_SHARED_LIBS=ON

      - name: Build
        run: cmake --build build --config Release